# Generated by Django 3.0.4 on 2020-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='Null', max_length=50)),
                ('surname', models.CharField(default='Null', max_length=60)),
                ('incentivisation_choice', models.CharField(choices=[('SM', 'Save Money'), ('HE', 'Help Environment')], default='SM', max_length=16)),
                ('goal', models.IntegerField(null=True)),
                ('phone_number', models.CharField(default='', max_length=13)),
                ('admin_type', models.CharField(choices=[('SA', 'super_admin'), ('AD', 'admin'), ('NA', 'non_admin')], default='NA', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energyused_ytd', models.IntegerField(default=0)),
                ('energyused_mtd', models.IntegerField(default=0)),
                ('energyused_day', models.IntegerField(default=0)),
            ],
        ),
    ]
