# Generated by Django 3.0.4 on 2020-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='goal',
            field=models.CharField(default='Saving Money', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='is_house_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_house_super',
            field=models.BooleanField(default=False),
        ),
    ]
