# Generated by Django 3.0.4 on 2020-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dwelling_code',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
