# Generated by Django 3.0.4 on 2020-04-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200417_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_unsecure',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account_unsecure',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account_unsecure',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account_unsecure',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account_unsecure',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account_unsecure',
            name='last_login',
        ),
    ]
