# Generated by Django 3.0.4 on 2020-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200326_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='goal',
            field=models.CharField(choices=[('SM', 'Save Money'), ('HE', 'Help Environment')], max_length=30),
        ),
    ]
