# Generated by Django 3.0.4 on 2020-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200331_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='house_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
