# Generated by Django 3.0.4 on 2020-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_house_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energyused_ytd', models.IntegerField(default=0)),
                ('energyused_mtd', models.IntegerField(default=0)),
                ('energyused_day', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='house_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='admin_type',
            field=models.CharField(choices=[('SA', 'super_admin'), ('AD', 'admin'), ('NA', 'non_admin')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='incentivisation_choice',
            field=models.CharField(choices=[('SM', 'Save Money'), ('HE', 'Help Environment')], default='SM', max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='Null', max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
