# Generated by Django 3.0.4 on 2020-04-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200417_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_unsecure',
            name='dwelling_code',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_unsecure',
            name='first_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_unsecure',
            name='password',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_unsecure',
            name='password2',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_unsecure',
            name='phone_number',
            field=models.CharField(default='null', max_length=13),
        ),
        migrations.AlterField(
            model_name='account_unsecure',
            name='surname',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='account_unsecure',
            name='username',
            field=models.CharField(default='null', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
