# Generated by Django 3.0.4 on 2020-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='house_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
