# Generated by Django 3.0.4 on 2020-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('dwelling_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dwelling_name', models.CharField(default='', max_length=50)),
                ('dwelling_code', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
