# Generated by Django 3.0.4 on 2020-04-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('dwelling_name', models.CharField(default='', max_length=50)),
                ('has_superAdmin', models.BooleanField(default=False)),
                ('dwelling_code', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='', max_length=50)),
                ('related_dwelling', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Dwelling.Dwelling')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(default=0, max_length=150)),
                ('related_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='Dwelling.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.CharField(default='', max_length=10485759)),
                ('humidity', models.CharField(default='', max_length=10485759)),
                ('temperature', models.CharField(default='', max_length=10485759)),
                ('related_room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='Dwelling.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_code', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='', max_length=50)),
                ('mac_address', models.CharField(default='', max_length=50)),
                ('energy_used', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Dwelling.Room')),
            ],
        ),
    ]
