# Generated by Django 3.0.4 on 2020-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='yeeto',
            field=models.IntegerField(default=0),
        ),
    ]
