# Generated by Django 3.0.4 on 2020-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac_adress',
            new_name='mac_address',
        ),
        migrations.RenameField(
            model_name='roomdata',
            old_name='light',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='dwelling',
            name='dwelling_id',
        ),
        migrations.RemoveField(
            model_name='dwelling',
            name='dwelling_members',
        ),
        migrations.RemoveField(
            model_name='dwelling',
            name='dwelling_progress',
        ),
        migrations.RemoveField(
            model_name='dwelling',
            name='dwelling_superUsers',
        ),
        migrations.RemoveField(
            model_name='roomdata',
            name='tempurature',
        ),
        migrations.AddField(
            model_name='device',
            name='energy_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwelling',
            name='has_superAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='dwelling_code',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
    ]
