# Generated by Django 3.0.4 on 2020-03-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='', max_length=50)),
                ('co2', models.IntegerField(default=0, null=True)),
                ('humidity', models.IntegerField(default=0, null=True)),
                ('dwelling_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dwelling.Dwelling')),
            ],
        ),
    ]
