# Generated by Django 3.0.4 on 2020-04-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_code',
            field=models.CharField(default='null', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='unnamed device', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Dwelling.Room'),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='dwelling_code',
            field=models.CharField(default='null', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='dwelling_name',
            field=models.CharField(default='unnamed dwelling', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='null', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='unnamed room', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='co2',
            field=models.CharField(default='null', max_length=10485759),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='humidity',
            field=models.CharField(default='null', max_length=10485759),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='related_room',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='Dwelling.Room'),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='temperature',
            field=models.CharField(default='null', max_length=10485759),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='related_room',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='Dwelling.Room'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(default='No Suggestion Calculated', max_length=150),
        ),
    ]
