# Generated by Django 3.0.4 on 2020-03-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dwelling_rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Dwelling.Dwelling'),
        ),
    ]
