# Generated by Django 3.0.4 on 2020-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0002_device_yeeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='yeeto',
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
