# Generated by Django 3.0.4 on 2020-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0003_auto_20200411_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
