# Generated by Django 3.0.4 on 2020-03-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0003_auto_20200308_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='', max_length=50)),
                ('mac_adress', models.CharField(default='', max_length=50)),
                ('room_devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='Dwelling.Room')),
            ],
        ),
    ]
