# Generated by Django 3.0.4 on 2020-03-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0004_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.CharField(default='', max_length=50000000)),
                ('humidity', models.CharField(default='', max_length=50000000)),
                ('tempurature', models.CharField(default='', max_length=50000000)),
                ('light', models.CharField(default='', max_length=50000000)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='room_devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Dwelling.Room'),
        ),
    ]
