# Generated by Django 3.0.4 on 2020-03-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0006_roomdata_rooms_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='humidity',
        ),
    ]
