# Generated by Django 3.0.4 on 2020-03-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0008_auto_20200308_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(default=0, max_length=150)),
                ('room_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='Dwelling.Room')),
            ],
        ),
    ]
