# Generated by Django 3.0.4 on 2020-03-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0009_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='Dwelling_progress',
            field=models.IntegerField(default=0),
        ),
    ]
