# Generated by Django 3.0.4 on 2020-03-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dwelling', '0010_dwelling_dwelling_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dwelling',
            old_name='Dwelling_progress',
            new_name='dwelling_progress',
        ),
    ]
