# Generated by Django 3.0.2 on 2020-01-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200127_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='AddDevice',
        ),
        migrations.AddField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.Room'),
        ),
    ]
