# Generated by Django 3.0.2 on 2020-01-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20200131_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='house.Room'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='house.Room'),
        ),
    ]
