# Generated by Django 3.0.2 on 2020-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Data',
            new_name='Readings',
        ),
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
