# Generated by Django 3.0.2 on 2020-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20200211_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='room',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
