# Generated by Django 3.0.2 on 2020-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20200211_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=60)),
                ('device_name', models.CharField(default='', max_length=50)),
                ('device_room', models.CharField(default='', max_length=50)),
                ('device_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwelling_id', models.CharField(default='XXXXX', max_length=16)),
                ('dwelling_name', models.CharField(default='', max_length=50)),
                ('users', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_id', models.IntegerField(blank=True, null=True)),
                ('reading_type', models.CharField(default='', max_length=50)),
                ('reading', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='name',
        ),
        migrations.AddField(
            model_name='login',
            name='dwelling_id',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='login',
            name='first_name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='login',
            name='incentivisation_choice',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='login',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='login',
            name='surname',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='weather_suggestion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
    ]
