# Generated by Django 3.0.2 on 2020-03-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20200302_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwellings',
            fields=[
                ('dwelling_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dwelling_name', models.CharField(default='', max_length=50)),
                ('dwelling_code', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('ranking', models.IntegerField(default=100)),
                ('money_saved', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='', max_length=50)),
                ('co2', models.IntegerField(default=0, null=True)),
                ('humidity', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('suggestion_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('suggestion_name', models.CharField(default='', max_length=150)),
                ('weather_suggestion', models.CharField(default=0, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=35)),
                ('surname', models.CharField(default='', max_length=35)),
                ('phone_number', models.CharField(default='', max_length=13)),
                ('incentivisation_choice', models.CharField(default='', max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Dwelling',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='name',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='room',
        ),
        migrations.RemoveField(
            model_name='login',
            name='dwelling_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='incentivisation_choice',
        ),
        migrations.RemoveField(
            model_name='login',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='login',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='readings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='readings',
            name='name',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='devices',
            name='device_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='readings',
            name='reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readings',
            name='reading_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='readings',
            name='reading_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
