# Generated by Django 3.0.2 on 2020-03-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_devices_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='room_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to='house.Rooms'),
        ),
    ]
